name: Prerelease

on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: prerelease-${{ github.sha }}
  cancel-in-progress: false

jobs:
  prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - run: npm ci
      - run: npm run build
      - run: npm run checkchange
      - name: Publish prerelease
        run: |
          commit_sha_short=$(git rev-parse --short "$GITHUB_SHA")
          npm run release -- --token "$NODE_AUTH_TOKEN" --no-push --prerelease-prefix "$commit_sha_short" --tag prerelease
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
